# Auto generated at 2009-08-28T03:30:05.487244
fields = {
	'OBJECT_FIELD_GUID':	0x0, # Size: 8, Type: GUID, Flags: PUBLIC
	'OBJECT_FIELD_TYPE':	0x8, # Size: 4, Type: INT, Flags: PUBLIC
	'OBJECT_FIELD_ENTRY':	0xc, # Size: 4, Type: INT, Flags: PUBLIC
	'OBJECT_FIELD_SCALE_X':	0x10, # Size: 4, Type: FLOAT, Flags: PUBLIC
	'OBJECT_FIELD_PADDING':	0x14, # Size: 4, Type: INT, Flags: NONE
	'OBJECT_END':	0x18,
	'ITEM_FIELD_OWNER':	0x18, # Size: 8, Type: GUID, Flags: PUBLIC
	'ITEM_FIELD_CONTAINED':	0x20, # Size: 8, Type: GUID, Flags: PUBLIC
	'ITEM_FIELD_CREATOR':	0x28, # Size: 8, Type: GUID, Flags: PUBLIC
	'ITEM_FIELD_GIFTCREATOR':	0x30, # Size: 8, Type: GUID, Flags: PUBLIC
	'ITEM_FIELD_STACK_COUNT':	0x38, # Size: 4, Type: INT, Flags: OWNER_ONLY, UNK2
	'ITEM_FIELD_DURATION':	0x3c, # Size: 4, Type: INT, Flags: OWNER_ONLY, UNK2
	'ITEM_FIELD_SPELL_CHARGES':	0x40, # Size: 20, Type: INT, Flags: OWNER_ONLY, UNK2
	'ITEM_FIELD_FLAGS':	0x54, # Size: 4, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_1_1':	0x58, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_1_3':	0x60, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_2_1':	0x64, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_2_3':	0x6c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_3_1':	0x70, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_3_3':	0x78, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_4_1':	0x7c, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_4_3':	0x84, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_5_1':	0x88, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_5_3':	0x90, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_6_1':	0x94, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_6_3':	0x9c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_7_1':	0xa0, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_7_3':	0xa8, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_8_1':	0xac, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_8_3':	0xb4, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_9_1':	0xb8, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_9_3':	0xc0, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_10_1':	0xc4, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_10_3':	0xcc, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_11_1':	0xd0, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_11_3':	0xd8, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_12_1':	0xdc, # Size: 8, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ENCHANTMENT_12_3':	0xe4, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'ITEM_FIELD_PROPERTY_SEED':	0xe8, # Size: 4, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_RANDOM_PROPERTIES_ID':	0xec, # Size: 4, Type: INT, Flags: PUBLIC
	'ITEM_FIELD_ITEM_TEXT_ID':	0xf0, # Size: 4, Type: INT, Flags: OWNER_ONLY
	'ITEM_FIELD_DURABILITY':	0xf4, # Size: 4, Type: INT, Flags: OWNER_ONLY, UNK2
	'ITEM_FIELD_MAXDURABILITY':	0xf8, # Size: 4, Type: INT, Flags: OWNER_ONLY, UNK2
	'ITEM_FIELD_CREATE_PLAYED_TIME':	0xfc, # Size: 4, Type: INT, Flags: PUBLIC
	'ITEM_END':	0x100,
	'CONTAINER_FIELD_NUM_SLOTS':	0x100, # Size: 4, Type: INT, Flags: PUBLIC
	'CONTAINER_ALIGN_PAD':	0x104, # Size: 4, Type: BYTES, Flags: NONE
	'CONTAINER_FIELD_SLOT_1':	0x108, # Size: 288, Type: GUID, Flags: PUBLIC
	'CONTAINER_END':	0x110,
	'UNIT_FIELD_CHARM':	0x18, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_SUMMON':	0x20, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_CRITTER':	0x28, # Size: 8, Type: GUID, Flags: PRIVATE
	'UNIT_FIELD_CHARMEDBY':	0x30, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_SUMMONEDBY':	0x38, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_CREATEDBY':	0x40, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_TARGET':	0x48, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_CHANNEL_OBJECT':	0x50, # Size: 8, Type: GUID, Flags: PUBLIC
	'UNIT_FIELD_BYTES_0':	0x58, # Size: 4, Type: BYTES, Flags: PUBLIC
	'UNIT_FIELD_HEALTH':	0x5c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER1':	0x60, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER2':	0x64, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER3':	0x68, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER4':	0x6c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER5':	0x70, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER6':	0x74, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER7':	0x78, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXHEALTH':	0x7c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER1':	0x80, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER2':	0x84, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER3':	0x88, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER4':	0x8c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER5':	0x90, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER6':	0x94, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MAXPOWER7':	0x98, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER':	0x9c, # Size: 28, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER':	0xb8, # Size: 28, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_LEVEL':	0xd4, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_FACTIONTEMPLATE':	0xd8, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_VIRTUAL_ITEM_SLOT_ID':	0xdc, # Size: 12, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_FLAGS':	0xe8, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_FLAGS_2':	0xec, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_AURASTATE':	0xf0, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_BASEATTACKTIME':	0xf4, # Size: 8, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_RANGEDATTACKTIME':	0xfc, # Size: 4, Type: INT, Flags: PRIVATE
	'UNIT_FIELD_BOUNDINGRADIUS':	0x100, # Size: 4, Type: FLOAT, Flags: PUBLIC
	'UNIT_FIELD_COMBATREACH':	0x104, # Size: 4, Type: FLOAT, Flags: PUBLIC
	'UNIT_FIELD_DISPLAYID':	0x108, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_NATIVEDISPLAYID':	0x10c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MOUNTDISPLAYID':	0x110, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_MINDAMAGE':	0x114, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
	'UNIT_FIELD_MAXDAMAGE':	0x118, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
	'UNIT_FIELD_MINOFFHANDDAMAGE':	0x11c, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
	'UNIT_FIELD_MAXOFFHANDDAMAGE':	0x120, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
	'UNIT_FIELD_BYTES_1':	0x124, # Size: 4, Type: BYTES, Flags: PUBLIC
	'UNIT_FIELD_PETNUMBER':	0x128, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_PET_NAME_TIMESTAMP':	0x12c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_PETEXPERIENCE':	0x130, # Size: 4, Type: INT, Flags: OWNER_ONLY
	'UNIT_FIELD_PETNEXTLEVELEXP':	0x134, # Size: 4, Type: INT, Flags: OWNER_ONLY
	'UNIT_DYNAMIC_FLAGS':	0x138, # Size: 4, Type: INT, Flags: DYNAMIC
	'UNIT_CHANNEL_SPELL':	0x13c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_MOD_CAST_SPEED':	0x140, # Size: 4, Type: FLOAT, Flags: PUBLIC
	'UNIT_CREATED_BY_SPELL':	0x144, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_NPC_FLAGS':	0x148, # Size: 4, Type: INT, Flags: DYNAMIC
	'UNIT_NPC_EMOTESTATE':	0x14c, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_STAT0':	0x150, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_STAT1':	0x154, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_STAT2':	0x158, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_STAT3':	0x15c, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_STAT4':	0x160, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POSSTAT0':	0x164, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POSSTAT1':	0x168, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POSSTAT2':	0x16c, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POSSTAT3':	0x170, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POSSTAT4':	0x174, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_NEGSTAT0':	0x178, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_NEGSTAT1':	0x17c, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_NEGSTAT2':	0x180, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_NEGSTAT3':	0x184, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_NEGSTAT4':	0x188, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_RESISTANCES':	0x18c, # Size: 28, Type: INT, Flags: PRIVATE, OWNER_ONLY, UNK3
	'UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE':	0x1a8, # Size: 28, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE':	0x1c4, # Size: 28, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_BASE_MANA':	0x1e0, # Size: 4, Type: INT, Flags: PUBLIC
	'UNIT_FIELD_BASE_HEALTH':	0x1e4, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_BYTES_2':	0x1e8, # Size: 4, Type: BYTES, Flags: PUBLIC
	'UNIT_FIELD_ATTACK_POWER':	0x1ec, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_ATTACK_POWER_MODS':	0x1f0, # Size: 4, Type: TWO_SHORT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_ATTACK_POWER_MULTIPLIER':	0x1f4, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_RANGED_ATTACK_POWER':	0x1f8, # Size: 4, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_RANGED_ATTACK_POWER_MODS':	0x1fc, # Size: 4, Type: TWO_SHORT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER':	0x200, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_MINRANGEDDAMAGE':	0x204, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_MAXRANGEDDAMAGE':	0x208, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POWER_COST_MODIFIER':	0x20c, # Size: 28, Type: INT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_POWER_COST_MULTIPLIER':	0x228, # Size: 28, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_MAXHEALTHMODIFIER':	0x244, # Size: 4, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
	'UNIT_FIELD_HOVERHEIGHT':	0x248, # Size: 4, Type: FLOAT, Flags: PUBLIC
	'UNIT_FIELD_PADDING':	0x24c, # Size: 4, Type: INT, Flags: NONE
	'UNIT_END':	0x250,
	'PLAYER_DUEL_ARBITER':	0x250, # Size: 8, Type: GUID, Flags: PUBLIC
	'PLAYER_FLAGS':	0x258, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_GUILDID':	0x25c, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_GUILDRANK':	0x260, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_BYTES':	0x264, # Size: 4, Type: BYTES, Flags: PUBLIC
	'PLAYER_BYTES_2':	0x268, # Size: 4, Type: BYTES, Flags: PUBLIC
	'PLAYER_BYTES_3':	0x26c, # Size: 4, Type: BYTES, Flags: PUBLIC
	'PLAYER_DUEL_TEAM':	0x270, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_GUILD_TIMESTAMP':	0x274, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_QUEST_LOG_1_1':	0x278, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_1_2':	0x27c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_1_3':	0x280, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_1_4':	0x284, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_2_1':	0x288, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_2_2':	0x28c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_2_3':	0x290, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_2_4':	0x294, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_3_1':	0x298, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_3_2':	0x29c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_3_3':	0x2a0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_3_4':	0x2a4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_4_1':	0x2a8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_4_2':	0x2ac, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_4_3':	0x2b0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_4_4':	0x2b4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_5_1':	0x2b8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_5_2':	0x2bc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_5_3':	0x2c0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_5_4':	0x2c4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_6_1':	0x2c8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_6_2':	0x2cc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_6_3':	0x2d0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_6_4':	0x2d4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_7_1':	0x2d8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_7_2':	0x2dc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_7_3':	0x2e0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_7_4':	0x2e4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_8_1':	0x2e8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_8_2':	0x2ec, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_8_3':	0x2f0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_8_4':	0x2f4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_9_1':	0x2f8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_9_2':	0x2fc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_9_3':	0x300, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_9_4':	0x304, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_10_1':	0x308, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_10_2':	0x30c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_10_3':	0x310, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_10_4':	0x314, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_11_1':	0x318, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_11_2':	0x31c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_11_3':	0x320, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_11_4':	0x324, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_12_1':	0x328, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_12_2':	0x32c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_12_3':	0x330, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_12_4':	0x334, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_13_1':	0x338, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_13_2':	0x33c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_13_3':	0x340, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_13_4':	0x344, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_14_1':	0x348, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_14_2':	0x34c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_14_3':	0x350, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_14_4':	0x354, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_15_1':	0x358, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_15_2':	0x35c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_15_3':	0x360, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_15_4':	0x364, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_16_1':	0x368, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_16_2':	0x36c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_16_3':	0x370, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_16_4':	0x374, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_17_1':	0x378, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_17_2':	0x37c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_17_3':	0x380, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_17_4':	0x384, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_18_1':	0x388, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_18_2':	0x38c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_18_3':	0x390, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_18_4':	0x394, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_19_1':	0x398, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_19_2':	0x39c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_19_3':	0x3a0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_19_4':	0x3a4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_20_1':	0x3a8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_20_2':	0x3ac, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_20_3':	0x3b0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_20_4':	0x3b4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_21_1':	0x3b8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_21_2':	0x3bc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_21_3':	0x3c0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_21_4':	0x3c4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_22_1':	0x3c8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_22_2':	0x3cc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_22_3':	0x3d0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_22_4':	0x3d4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_23_1':	0x3d8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_23_2':	0x3dc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_23_3':	0x3e0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_23_4':	0x3e4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_24_1':	0x3e8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_24_2':	0x3ec, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_24_3':	0x3f0, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_24_4':	0x3f4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_25_1':	0x3f8, # Size: 4, Type: INT, Flags: GROUP_ONLY
	'PLAYER_QUEST_LOG_25_2':	0x3fc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_QUEST_LOG_25_3':	0x400, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_QUEST_LOG_25_4':	0x404, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_VISIBLE_ITEM_1_ENTRYID':	0x408, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_1_ENCHANTMENT':	0x40c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_2_ENTRYID':	0x410, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_2_ENCHANTMENT':	0x414, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_3_ENTRYID':	0x418, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_3_ENCHANTMENT':	0x41c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_4_ENTRYID':	0x420, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_4_ENCHANTMENT':	0x424, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_5_ENTRYID':	0x428, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_5_ENCHANTMENT':	0x42c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_6_ENTRYID':	0x430, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_6_ENCHANTMENT':	0x434, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_7_ENTRYID':	0x438, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_7_ENCHANTMENT':	0x43c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_8_ENTRYID':	0x440, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_8_ENCHANTMENT':	0x444, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_9_ENTRYID':	0x448, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_9_ENCHANTMENT':	0x44c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_10_ENTRYID':	0x450, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_10_ENCHANTMENT':	0x454, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_11_ENTRYID':	0x458, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_11_ENCHANTMENT':	0x45c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_12_ENTRYID':	0x460, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_12_ENCHANTMENT':	0x464, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_13_ENTRYID':	0x468, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_13_ENCHANTMENT':	0x46c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_14_ENTRYID':	0x470, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_14_ENCHANTMENT':	0x474, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_15_ENTRYID':	0x478, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_15_ENCHANTMENT':	0x47c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_16_ENTRYID':	0x480, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_16_ENCHANTMENT':	0x484, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_17_ENTRYID':	0x488, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_17_ENCHANTMENT':	0x48c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_18_ENTRYID':	0x490, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_18_ENCHANTMENT':	0x494, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_19_ENTRYID':	0x498, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_VISIBLE_ITEM_19_ENCHANTMENT':	0x49c, # Size: 4, Type: TWO_SHORT, Flags: PUBLIC
	'PLAYER_CHOSEN_TITLE':	0x4a0, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_FAKE_INEBRIATION':	0x4a4, # Size: 4, Type: INT, Flags: PUBLIC
	'PLAYER_FIELD_INV_SLOT_HEAD':	0x4a8, # Size: 184, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_PACK_SLOT_1':	0x560, # Size: 128, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_BANK_SLOT_1':	0x5e0, # Size: 224, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_BANKBAG_SLOT_1':	0x6c0, # Size: 56, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_VENDORBUYBACK_SLOT_1':	0x6f8, # Size: 96, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_KEYRING_SLOT_1':	0x758, # Size: 256, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_CURRENCYTOKEN_SLOT_1':	0x858, # Size: 256, Type: GUID, Flags: PRIVATE
	'PLAYER_FARSIGHT':	0x958, # Size: 8, Type: GUID, Flags: PRIVATE
	'PLAYER__FIELD_KNOWN_TITLES':	0x960, # Size: 8, Type: GUID, Flags: PRIVATE
	'PLAYER__FIELD_KNOWN_TITLES1':	0x968, # Size: 8, Type: GUID, Flags: PRIVATE
	'PLAYER__FIELD_KNOWN_TITLES2':	0x970, # Size: 8, Type: GUID, Flags: PRIVATE
	'PLAYER_FIELD_KNOWN_CURRENCIES':	0x978, # Size: 8, Type: GUID, Flags: PRIVATE
	'PLAYER_XP':	0x980, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_NEXT_LEVEL_XP':	0x984, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_SKILL_INFO_1_1':	0x988, # Size: 1536, Type: TWO_SHORT, Flags: PRIVATE
	'PLAYER_CHARACTER_POINTS1':	0xf88, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_CHARACTER_POINTS2':	0xf8c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_TRACK_CREATURES':	0xf90, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_TRACK_RESOURCES':	0xf94, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_BLOCK_PERCENTAGE':	0xf98, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_DODGE_PERCENTAGE':	0xf9c, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_PARRY_PERCENTAGE':	0xfa0, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_EXPERTISE':	0xfa4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_OFFHAND_EXPERTISE':	0xfa8, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_CRIT_PERCENTAGE':	0xfac, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_RANGED_CRIT_PERCENTAGE':	0xfb0, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_OFFHAND_CRIT_PERCENTAGE':	0xfb4, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_SPELL_CRIT_PERCENTAGE1':	0xfb8, # Size: 28, Type: FLOAT, Flags: PRIVATE
	'PLAYER_SHIELD_BLOCK':	0xfd4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE':	0xfd8, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_EXPLORED_ZONES_1':	0xfdc, # Size: 512, Type: BYTES, Flags: PRIVATE
	'PLAYER_REST_STATE_EXPERIENCE':	0x11dc, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_COINAGE':	0x11e0, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_DAMAGE_DONE_POS':	0x11e4, # Size: 28, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_DAMAGE_DONE_NEG':	0x1200, # Size: 28, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_DAMAGE_DONE_PCT':	0x121c, # Size: 28, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_HEALING_DONE_POS':	0x1238, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_HEALING_PCT':	0x123c, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_HEALING_DONE_PCT':	0x1240, # Size: 4, Type: FLOAT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_TARGET_RESISTANCE':	0x1244, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE':	0x1248, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_BYTES':	0x124c, # Size: 4, Type: BYTES, Flags: PRIVATE
	'PLAYER_AMMO_ID':	0x1250, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_SELF_RES_SPELL':	0x1254, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_PVP_MEDALS':	0x1258, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_BUYBACK_PRICE_1':	0x125c, # Size: 48, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_BUYBACK_TIMESTAMP_1':	0x128c, # Size: 48, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_KILLS':	0x12bc, # Size: 4, Type: TWO_SHORT, Flags: PRIVATE
	'PLAYER_FIELD_TODAY_CONTRIBUTION':	0x12c0, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_YESTERDAY_CONTRIBUTION':	0x12c4, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_LIFETIME_HONORBALE_KILLS':	0x12c8, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_BYTES2':	0x12cc, # Size: 4, Type: NONE, Flags: PRIVATE
	'PLAYER_FIELD_WATCHED_FACTION_INDEX':	0x12d0, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_COMBAT_RATING_1':	0x12d4, # Size: 100, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_ARENA_TEAM_INFO_1_1':	0x1338, # Size: 84, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_HONOR_CURRENCY':	0x138c, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_ARENA_CURRENCY':	0x1390, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_MAX_LEVEL':	0x1394, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_DAILY_QUESTS_1':	0x1398, # Size: 100, Type: INT, Flags: PRIVATE
	'PLAYER_RUNE_REGEN_1':	0x13fc, # Size: 16, Type: FLOAT, Flags: PRIVATE
	'PLAYER_NO_REAGENT_COST_1':	0x140c, # Size: 12, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_GLYPH_SLOTS_1':	0x1418, # Size: 24, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_GLYPHS_1':	0x1430, # Size: 24, Type: INT, Flags: PRIVATE
	'PLAYER_GLYPHS_ENABLED':	0x1448, # Size: 4, Type: INT, Flags: PRIVATE
	'PLAYER_FIELD_PADDING':	0x144c, # Size: 4, Type: INT, Flags: NONE
	'PLAYER_END':	0x1450,
	'OBJECT_FIELD_CREATED_BY':	0x18, # Size: 8, Type: GUID, Flags: PUBLIC
	'GAMEOBJECT_DISPLAYID':	0x20, # Size: 4, Type: INT, Flags: PUBLIC
	'GAMEOBJECT_FLAGS':	0x24, # Size: 4, Type: INT, Flags: PUBLIC
	'GAMEOBJECT_PARENTROTATION':	0x28, # Size: 16, Type: FLOAT, Flags: PUBLIC
	'GAMEOBJECT_DYNAMIC':	0x38, # Size: 4, Type: TWO_SHORT, Flags: DYNAMIC
	'GAMEOBJECT_FACTION':	0x3c, # Size: 4, Type: INT, Flags: PUBLIC
	'GAMEOBJECT_LEVEL':	0x40, # Size: 4, Type: INT, Flags: PUBLIC
	'GAMEOBJECT_BYTES_1':	0x44, # Size: 4, Type: BYTES, Flags: PUBLIC
	'GAMEOBJECT_END':	0x48,
	'DYNAMICOBJECT_CASTER':	0x18, # Size: 8, Type: GUID, Flags: PUBLIC
	'DYNAMICOBJECT_BYTES':	0x20, # Size: 4, Type: BYTES, Flags: PUBLIC
	'DYNAMICOBJECT_SPELLID':	0x24, # Size: 4, Type: INT, Flags: PUBLIC
	'DYNAMICOBJECT_RADIUS':	0x28, # Size: 4, Type: FLOAT, Flags: PUBLIC
	'DYNAMICOBJECT_CASTTIME':	0x2c, # Size: 4, Type: INT, Flags: PUBLIC
	'DYNAMICOBJECT_END':	0x30,
	'CORPSE_FIELD_OWNER':	0x18, # Size: 8, Type: GUID, Flags: PUBLIC
	'CORPSE_FIELD_PARTY':	0x20, # Size: 8, Type: GUID, Flags: PUBLIC
	'CORPSE_FIELD_DISPLAY_ID':	0x28, # Size: 4, Type: INT, Flags: PUBLIC
	'CORPSE_FIELD_ITEM':	0x2c, # Size: 76, Type: INT, Flags: PUBLIC
	'CORPSE_FIELD_BYTES_1':	0x78, # Size: 4, Type: BYTES, Flags: PUBLIC
	'CORPSE_FIELD_BYTES_2':	0x7c, # Size: 4, Type: BYTES, Flags: PUBLIC
	'CORPSE_FIELD_GUILD':	0x80, # Size: 4, Type: INT, Flags: PUBLIC
	'CORPSE_FIELD_FLAGS':	0x84, # Size: 4, Type: INT, Flags: PUBLIC
	'CORPSE_FIELD_DYNAMIC_FLAGS':	0x88, # Size: 4, Type: INT, Flags: DYNAMIC
	'CORPSE_FIELD_PAD':	0x8c, # Size: 4, Type: INT, Flags: NONE
	'CORPSE_END':	0x90,
}
